SELECT p.PRODUCT_CODE, sub1.SUM*p.price AS SALES
FROM (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SUM
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
    ) sub1
JOIN PRODUCT AS p
ON sub1.PRODUCT_ID = p.PRODUCT_ID
ORDER BY SALES DESC, p.PRODUCT_CODE ASC
