SELECT sub.ANIMAL_ID, sub.NAME
from (
SELECT outs.ANIMAL_ID, outs.NAME, ins.ANIMAL_ID AS ins_ANIMAL_ID
FROM ANIMAL_OUTS AS outs
LEFT JOIN ANIMAL_INS AS ins
on outs.ANIMAL_ID = ins.ANIMAL_ID) AS sub
where sub.ins_ANIMAL_ID IS NULL;

# SELECT outs.ANIMAL_ID, outs.NAME, ins.ANIMAL_ID AS ins_ANIMAL_ID
# FROM ANIMAL_OUTS AS outs
# LEFT JOIN ANIMAL_INS AS ins
# on outs.ANIMAL_ID = ins.ANIMAL_ID