SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE*O_SUB.TOTAL_AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT AS P
JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
    GROUP BY PRODUCT_ID) AS O_SUB
ON P.PRODUCT_ID = O_SUB.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC;

# SELECT PRODUCT_ID, SUM(AMOUNT)
# FROM (SELECT PRODUCT_ID, AMOUNT
#     FROM FOOD_ORDER
#     WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31') AS tbl
# GROUP BY PRODUCT_ID;
