SELECT sub1.SCORE, sub1.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM (
    SELECT SUM(SCORE) AS SCORE, EMP_NO
    FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY SCORE DESC
    LIMIT 1
) AS sub1
JOIN HR_EMPLOYEES
    ON sub1.EMP_NO = HR_EMPLOYEES.EMP_NO
