select B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
from BOOK as B
JOIN AUTHOR as A
ON B.AUTHOR_ID = A.AUTHOR_ID
where B.CATEGORY="경제"
ORDER BY B.PUBLISHED_DATE ASC