SELECT SUB.p AS PRICE_GROUP, COUNT(SUB.CODE) AS PRODUCTS
FROM
    (select PRODUCT_CODE AS CODE, PRICE-(price%10000) AS p
    FROM PRODUCT
     ) AS SUB
GROUP BY SUB.p
ORDER BY PRICE_GROUP


# SELECT FLOOR(price/10000) * 10000 AS PRICE_GROUP, COUNT(*) AS PRODUCTS
# FROM PRODUCT
# GROUP BY FLOOR(price/10000) * 10000
# ORDER BY PRICE_GROUP